version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672","15672:15672"]

  postgres-orders:
    image: postgres:15
    environment: POSTGRES_DB=ordersdb,POSTGRES_USER=app,POSTGRES_PASSWORD=secret
    ports: ["5432:5432"]

  postgres-payments:
    image: postgres:15
    environment: POSTGRES_DB=paymentsdb,POSTGRES_USER=app,POSTGRES_PASSWORD=secret
    ports: ["5433:5432"]

  order-service:
    build: ./order-service
    ports: ["8081:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-orders:5432/ordersdb
      SPRING_RABBITMQ_HOST: rabbitmq

  payment-service:
    build: ./payment-service
    ports: ["8082:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payments:5432/paymentsdb
      SPRING_RABBITMQ_HOST: rabbitmq
